replicaCount: 1
app:
  image:
    name: cupofjavatech/iron-fist
    tag: v1

service:
  containerPort: 8081
  targetPort: 8081

env:
  name1: URL_RED_HOOD
  value1: "http://redhood-service:8082/red-hood"
  enabled1: "true"