apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-named-template
  {{- template "helm-demo-namedtemplate.labels" . }}
  {{- include "helm-demo-namedtemplate.redhood" .  | indent 4 }}
data:
  myValue: "Named Template Value"
{{- include "helm-demo-namedtemplate.redhood" .  | indent 2 }}