apiVersion: v1
kind: ConfigMap
metadata:
  name: built-in-object-configmap
data:
  {{- if .Values.favorite.wantOrangeJuice }}
  drink: {{ .Values.favorite.drink }}
  {{- else }}
  fruit: {{ .Values.favorite.fruit }}
  {{- end }}
  food:
  {{- if eq .Values.favorite.food "pizza" }}
  {{- .Values.favorite.food | indent 1 }}
  {{- else }}
  {{- .Values.favorite.fruit | indent 2 }}
  {{- end }}
  {{- /* eq ne lt gt and */}}
  food_1:
  {{- if and ( eq .Values.favorite.food "pizza-1") ( eq .Values.favorite.fruit "Banana" ) }}
  {{- "Like Pizza and Banana" | indent 1 }}
  {{- else }}
  {{- "I don't like anything" | indent 1 }}
  {{- end }}